import ifcopenshell
import ifcopenshell.util.element
import ifcopenshell.util.selector
import ifcopenshell.geom
import numpy as np
import json
import time
import os
import argparse

start_time = time.time()

# --- UTILITY FUNCTIONS FOR JSON SERIALIZATION ---
def remove_duplicate_entities(ifc_entities):
    seen = set()
    new_entities = {}
    for ifc_class, entities in ifc_entities.items():
        new_class_entities = {}
        for entity_id, data in entities.items():
            if entity_id not in seen:
                seen.add(entity_id)
                new_class_entities[entity_id] = data
        new_entities[ifc_class] = new_class_entities
    return new_entities

def handle_ifcopenshell_entity(obj):
    """Fallback for objects not directly serializable by JSON."""
    if isinstance(obj, ifcopenshell.entity_instance):
        return str(obj)
    raise TypeError(f"Type {type(obj)} not serializable")

def sanitize_ifc_data(obj):
    """Recursively convert non-JSON-serializable objects (e.g., IFC entities) to strings or basic types."""
    if isinstance(obj, dict):
        return {k: sanitize_ifc_data(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [sanitize_ifc_data(e) for e in obj]
    elif isinstance(obj, ifcopenshell.entity_instance):
        return str(obj)
    else:
        return obj

# --- GEOMETRY UTILS ---

# Set up the geometry settings (using world coordinates)
geom_settings = ifcopenshell.geom.settings()
geom_settings.set(geom_settings.USE_WORLD_COORDS, True)

def compute_bounding_box(shape):
    """
    Given a shape generated by ifcopenshell.geom.create_shape,
    compute its axis-aligned bounding box.
    Returns a dictionary with "min" and "max" keys.
    """
    vertices = np.array(shape.geometry.verts)
    if vertices.size == 0:
        raise ValueError("No vertices found in geometry.")
    points = vertices.reshape((-1, 3))
    min_coords = points.min(axis=0)
    max_coords = points.max(axis=0)
    # Convert numpy arrays to lists for JSON serialization.
    return {"min": min_coords.tolist(), "max": max_coords.tolist()}

def process_ifc_file(ifc_file_path):
    """Process the IFC file and output a JSON file with the extracted data."""
    start_time = time.time()

    model = ifcopenshell.open(ifc_file_path)

    ifc_classes_to_process = [
        "IfcSpace"
    ]

    IFC_ENTITIES = {}

    for ifc_class in ifc_classes_to_process:
        entities = model.by_type(ifc_class)
        IFC_ENTITIES[ifc_class] = {}

        for entity in entities:
            info = entity.get_info()  # Basic attributes of the entity.
            psets = ifcopenshell.util.element.get_psets(entity)  # Property sets.
            base_quantities = psets.get("BaseQuantities")
            level_info = psets.get("Room Schedule Leopold Point")
            if base_quantities is None:
                # Optionally skip entities without "BaseQuantities"
                continue

            entity_id = info.get("id", str(entity))

            # --- BUILD THE ENTITY DICTIONARY ---
            entity_dict = {
                "info": info,
                "BaseQuantities": base_quantities,
                "Room Schedule Leopold Point": level_info
            }

            IFC_ENTITIES[ifc_class][entity_id] = entity_dict

    IFC_ENTITIES = remove_duplicate_entities(IFC_ENTITIES)
    # --- SANITIZE THE DATA FOR JSON ---
    IFC_ENTITIES_CLEAN = sanitize_ifc_data(IFC_ENTITIES)

    base_name = os.path.splitext(os.path.basename(ifc_file_path))[0]

    total_summary = sum_gross_area_by_level(IFC_ENTITIES_CLEAN)

    balcony_summary = sum_balcony_gross_area_by_level(IFC_ENTITIES_CLEAN)

    net_summary = compute_net_area_by_level(total_summary, balcony_summary)
    
    net_summary_file = os.path.join(os.path.dirname(ifc_file_path), f"results/{base_name}_total_area_net_summary.json")
    with open(net_summary_file, "w", encoding="utf-8") as f:
        json.dump(net_summary, f, indent=4, ensure_ascii=False)
    print(f"Saved net area summary (total minus balconies) by level to {net_summary_file}")

    end_time = time.time()
    latency = end_time - start_time
    print("Latency:", latency)

def sum_gross_area_by_level(ifc_entities):
    """
    Iterate through the IFC entities (which are already filtered to spaces)
    and sum up the GrossFloorArea from the BaseQuantities property for each level (from
    the "Room Schedule Leopold Point" property).
    """
    level_area_sums = {}
    for ifc_class, entities in ifc_entities.items():
        for entity_id, entity_data in entities.items():
            if "BaseQuantities" in entity_data and "Room Schedule Leopold Point" in entity_data:
                base_quantities = entity_data["BaseQuantities"]
                room_schedule = entity_data["Room Schedule Leopold Point"]
                if base_quantities and "GrossFloorArea" in base_quantities and room_schedule and "Level" in room_schedule:
                    level = room_schedule["Level"]
                    gross_area = base_quantities["GrossFloorArea"]
                    level_area_sums[level] = level_area_sums.get(level, 0) + gross_area
    return level_area_sums

def sum_balcony_gross_area_by_level(ifc_entities):
    """
    Iterate through the IFC entities, filter to those that are marked as balconies (via the "LongName" property),
    and sum up the GrossFloorArea for each level.
    """
    level_area_sums = {}
    for ifc_class, entities in ifc_entities.items():
        for entity_id, entity_data in entities.items():
            info = entity_data.get("info", {})
            if info.get("LongName", "").lower() != "balcony":
                continue

            if "BaseQuantities" in entity_data and "Room Schedule Leopold Point" in entity_data:
                base_quantities = entity_data["BaseQuantities"]
                room_schedule = entity_data["Room Schedule Leopold Point"]
                # Ensure the keys exist
                if base_quantities and "GrossFloorArea" in base_quantities and room_schedule and "Level" in room_schedule:
                    level = room_schedule["Level"]
                    gross_area = base_quantities["GrossFloorArea"]
                    # Sum the gross area for this level
                    level_area_sums[level] = level_area_sums.get(level, 0) + gross_area
    return level_area_sums

def compute_net_area_by_level(total_area, balcony_area):
    """
    For each level, deduct the balcony area from the total gross floor area.
    Additionally, add a field 'number_of_floor' which is the number of levels.
    Returns a dictionary containing:
      - 'net_area': a dictionary mapping each level to its net area, and
      - 'number_of_floor': the number of levels.
    """
    net_area = {}
    for level, total in total_area.items():
        balcony = balcony_area.get(level, 0)
        net_area[level] = total - balcony

    net_summary = {
        "net_area": net_area,
        "number_of_floors": len(net_area)
    }
    return net_summary


def main():
    parser = argparse.ArgumentParser(
        description="Process an IFC file and output its entities as a JSON file."
    )
    parser.add_argument(
        "ifc_file",
        help="Path to the IFC file to process."
    )
    args = parser.parse_args()
    process_ifc_file(args.ifc_file)

if __name__ == '__main__':
    main()
